Aerodactyl: Add IMS jars to PRODUCT_BOOT_JARS
These jars were system_ext_specific in the vendor Android.bp, which
caused GSI validation to reject them when added to PRODUCT_BOOT_JARS.
The vendor Android.bp has been patched to remove system_ext_specific
from the IMS jars (they install to system/framework/ anyway).

Fixes: NoClassDefFoundError: com.mediatek.ims.internal.IMtkImsService$Stub